# Generated by Django 3.2.5 on 2021-08-05 10:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('inventory', '0004_auto_20210801_0801'),
        ('organization', '0002_delete_followup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('updating_date', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to='organization.organization')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quotes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='QuoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count_of_product', models.PositiveIntegerField(default=1)),
                ('price_before_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_after_tax', models.DecimalField(decimal_places=2, max_digits=10)),
                ('off_percent', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quote_items', to='inventory.product')),
                ('quote', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='quote.quote')),
            ],
        ),
    ]
