# Generated by Django 3.2.5 on 2021-08-12 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0002_auto_20210805_1749'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quote',
            options={'ordering': ['-registration_date']},
        ),
    ]
