# Generated by Django 3.2.5 on 2021-08-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quote', '0003_alter_quote_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=11, null=True),
        ),
    ]
