# Generated by Django 3.2.5 on 2021-07-28 22:39

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Province',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'ordering': ('-name',),
            },
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('phone', models.CharField(max_length=50, unique=True, validators=[django.core.validators.RegexValidator(regex='^(\\+98?)?{?(0?9[0-9]{9,9}}?)$')])),
                ('workers_count', models.PositiveIntegerField(default=0)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=50, validators=[django.core.validators.RegexValidator(regex='^(\\+98?)?{?(0?9[0-9]{9,9}}?)$')])),
                ('contact_email', models.EmailField(max_length=254)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('products', models.ManyToManyField(related_name='organizations', to='organization.OrganizationProduct')),
                ('province', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organizations', to='organization.province')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registered_organization', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-registration_date', '-name'),
            },
        ),
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='organization.organization')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
