# Generated by Django 3.2.5 on 2021-08-05 09:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FollowUp',
        ),
    ]
