# Generated by Django 3.2.5 on 2021-07-29 04:31

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('tax', models.BooleanField(default=True)),
                ('pdf_file', models.FileField(upload_to='files/pdf_files/%Y/%m/%d', validators=[inventory.validators.validate_pdf])),
                ('pic_file', models.FileField(upload_to='files/pic_files/%Y/%m/%d', validators=[inventory.validators.validate_pic])),
                ('technical_report', models.TextField()),
                ('related_products', models.ManyToManyField(related_name='related_products', to='organization.OrganizationProduct')),
            ],
            options={
                'ordering': ('-price', '-name'),
            },
        ),
    ]
