# Generated by Django 3.2.5 on 2021-07-29 16:28

from django.db import migrations, models
import inventory.validators


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_auto_20210729_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(upload_to='files/pdf_files/%Y/%m/%d', validators=[inventory.validators.validate_pdf]),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic_file',
            field=models.FileField(upload_to='files/pic_files/%Y/%m/%d', validators=[inventory.validators.validate_pic]),
        ),
    ]
