# Generated by Django 3.2.5 on 2021-08-01 08:01

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_auto_20210729_1628'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pdf_file',
            field=models.FileField(upload_to='files/pdf_files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])]),
        ),
        migrations.AlterField(
            model_name='product',
            name='pic_file',
            field=models.FileField(upload_to='files/pic_files/%Y/%m/%d', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'svg'])]),
        ),
    ]
