# Generated by Django 3.2.5 on 2021-08-05 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0002_delete_followup'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FollowUp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('report', models.TextField()),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to='organization.organization')),
                ('registrar', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='followups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('date',),
            },
        ),
    ]
